// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as accent$0 from "../../accent/models.js";

/**
 * GetTheme returns the current device theme info.
 */
export function GetTheme(): $CancellablePromise<accent$0.Info> {
    return $Call.ByID(550356952).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = accent$0.Info.createFrom;
