// Code generated by traygen. DO NOT EDIT.

package trayicons

import (
	"embed"
	"fmt"
	"github.com/smegg99/s99wails/tray"
)

// Status selects a pregenerated tray icon state.
type Status string

const (
	StatusIdle      Status = "idle"
	StatusRecording Status = "recording"
)

//go:embed dark/linux-png-fallback light/linux-png-fallback
var FS embed.FS

// Icon returns the primary-size PNG for the theme/status combination.
func Icon(dark bool, status Status) ([]byte, error) {
	theme := "light"
	if dark {
		theme = "dark"
	}
	return FS.ReadFile(fmt.Sprintf("%s/linux-png-fallback/smeggtuner-tray-%s-%s.png", theme, theme, status))
}

// ForStatus adapts a status to the s99wails tray icon interface:
//
//	manager.SetIcons(ForStatus(StatusError))
func ForStatus(status Status) tray.IconsFunc {
	return func(dark bool) ([]byte, error) {
		return Icon(dark, status)
	}
}
