// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  {
    ignores: [
      '.nuxt/**',
      '.output/**',
      'dist/**',
      'bindings/**',
      // Emitted by s99wails frontendgen, next to the Wails bindings and for the
      // same reason: generated, version locked to the Go module, and not ours to
      // restyle. Regenerated by `go generate ./...`.
      'app/composables/s99wails/**',
      'coverage/**',
      'node_modules/**',
    ],
  },
  {
    files: ['**/*.{js,ts,tsx,vue}'],
    rules: {
      'vue/multi-word-component-names': 'off',
      // Vuetify uses dotted slot names (e.g. #item.status) on data tables.
      'vue/valid-v-slot': ['error', { allowModifiers: true }],
      // A couple of justified casts in infra code (vite plugin, event payloads).
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      'no-console': 'warn',
    },
  },
)
