// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Info holds a point-in-time snapshot of device-level theme settings.
 */
export class Info {
    "accent_color": string;
    "dark_mode": boolean;
    "scheme": Scheme;
    "accent_watch_supported": boolean;

    /** Creates a new Info instance. */
    constructor($$source: Partial<Info> = {}) {
        if (!("accent_color" in $$source)) {
            this["accent_color"] = "";
        }
        if (!("dark_mode" in $$source)) {
            this["dark_mode"] = false;
        }
        if (!("scheme" in $$source)) {
            this["scheme"] = Scheme.$zero;
        }
        if (!("accent_watch_supported" in $$source)) {
            this["accent_watch_supported"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     */
    static createFrom($$source: any = {}): Info {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info($$parsedSource as Partial<Info>);
    }
}

/**
 * Scheme is the OS color-scheme preference. Unlike a plain dark-mode bool it
 * preserves "no preference", which is a real state on Linux.
 */
export enum Scheme {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SchemeNoPreference = "no-preference",
    SchemeLight = "light",
    SchemeDark = "dark",
};
