// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service opens URLs in the user's default browser.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * OpenURL opens the given URL in the user's default system browser.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(3018895027, url);
}
