// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as record$0 from "../../../../../smegg.me/smeggtuner/services/record/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as session$0 from "../../../../../smegg.me/smeggtuner/services/session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as tuner$0 from "../../../../../smegg.me/smeggtuner/services/tuner/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "playback:position": tuner$0.PlaybackDTO;
            "record:state": record$0.StateDTO;
            "record:table": record$0.TableDTO;
            "session:active": session$0.ActiveDTO;
            "session:saveFailed": session$0.ErrorDTO;
            "tuner:measurement": tuner$0.MeasurementDTO;
            "tuner:settings": tuner$0.SettingsDTO;
            "tuner:state": tuner$0.StateDTO;
        }
    }
}
