//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as record$0 from "../../../../../smegg.me/smeggtuner/services/record/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../../../../../smegg.me/smeggtuner/services/session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tuner$0 from "../../../../../smegg.me/smeggtuner/services/tuner/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "playback:position": $$createType0,
        "record:state": $$createType1,
        "record:table": $$createType2,
        "session:active": $$createType3,
        "session:saveFailed": $$createType4,
        "tuner:measurement": $$createType5,
        "tuner:settings": $$createType6,
        "tuner:state": $$createType7,
    }));
}

// Private type creation functions
const $$createType0 = tuner$0.PlaybackDTO.createFrom;
const $$createType1 = record$0.StateDTO.createFrom;
const $$createType2 = record$0.TableDTO.createFrom;
const $$createType3 = session$0.ActiveDTO.createFrom;
const $$createType4 = session$0.ErrorDTO.createFrom;
const $$createType5 = tuner$0.MeasurementDTO.createFrom;
const $$createType6 = tuner$0.SettingsDTO.createFrom;
const $$createType7 = tuner$0.StateDTO.createFrom;

configure();
