// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package config

type Config struct {
	Preferences Preferences `json:"preferences"`

	Logger LoggerConfig `json:"logger"`

	Audio Audio `json:"audio"`

	Tuner Tuner `json:"tuner"`

	Report Report `json:"report"`

	Storage Storage `json:"storage"`

	Engine Engine `json:"engine"`
}

type Preferences struct {
	Theme string `json:"theme"`

	// accent_mode "auto" follows the desktop's own accent (via s99wails), falling
	// back to the app's built-in blue where the OS exposes none; "custom" uses
	// accent_color instead.
	AccentMode string `json:"accent_mode"`

	AccentColor string `json:"accent_color"`

	Language string `json:"language"`

	CloseToTray bool `json:"close_to_tray"`
}

type LoggerConfig struct {
	Verbose bool `json:"verbose"`

	NoColor bool `json:"no_color"`

	EnableFiles bool `json:"enable_files"`

	Dir string `json:"dir"`

	Prefix string `json:"prefix"`

	Level string `json:"level"`

	MaxSizeMb int64 `json:"max_size_mb"`

	MaxBackups int64 `json:"max_backups"`

	MaxAgeDays int64 `json:"max_age_days"`

	LogName string `json:"log_name"`

	Compression string `json:"compression"`

	LocalTime bool `json:"local_time"`
}

type Audio struct {
	DeviceID string `json:"device_id"`

	HumFilter50 bool `json:"hum_filter_50"`

	HumFilter60 bool `json:"hum_filter_60"`

	ClockPPM float64 `json:"clock_ppm"`
}

// tolerance is the reference technician's own figure: "najlepiej glosy czyste by
// byly z dokladnoscia do centa". beat_tolerance is deliberately looser, and for
// arithmetic rather than taste: a beat carries BOTH its reeds' errors, so a pair
// at +1 and -1 cents is two cents apart while each reed passes its own one cent
// window. See core/target.DefaultBeatTolerance.
type Tuner struct {
	A4 float64 `json:"a4"`

	Unit string `json:"unit"`

	ScaleNaming string `json:"scale_naming"`

	ErrorReference string `json:"error_reference"`

	StopAfterLock bool `json:"stop_after_lock"`

	ContinuousUpdateManual bool `json:"continuous_update_manual"`

	Tolerance float64 `json:"tolerance"`

	BeatTolerance float64 `json:"beat_tolerance"`

	// How long the reference tone plays, in milliseconds, when the note strip is
	// asked to sound a note. Ten seconds, per Dirk's "play the note for ten
	// seconds"; it is also how long the recorder treats the room as contaminated.
	ToneDurationMs int64 `json:"tone_duration_ms"`

	// The calibration capture window, in milliseconds: how long the Capture key
	// stays live after the engine locks onto a note while calibrating an
	// instrument, so the reading can be taken without racing a lock that comes
	// and goes. Longer than a lock hold on purpose - calibration is a deliberate,
	// one-note-at-a-time job.
	CalibrationCaptureMs int64 `json:"calibration_capture_ms"`

	// note_sounds lets the note strip speak: hold a note and hear it, which is how
	// a technician finds the key he has pinned on an instrument whose layout he
	// does not know by heart (Dirk's manual, chapter 15).
	//
	// It defaults OFF, and that is not timidity. This tuner listens through a
	// microphone, so a tone out of the speakers is a tone the microphone hears.
	// The engine cannot tell it from the instrument, and a take recorded while it
	// sounds would put a reed on a printed report that does not exist. The RECORDER
	// is what refuses that (services/tuner.observe), but a feature that can quietly
	// contaminate a measurement should be reached for, not stumbled into.
	NoteSounds bool `json:"note_sounds"`
}

type Report struct {
	CompanyName string `json:"company_name"`

	CompanyAddress string `json:"company_address"`

	CompanyWebsite string `json:"company_website"`

	LogoPath string `json:"logo_path"`
}

// db_path defaults to a @{datadir:...} reference so one config file means the
// right thing everywhere: the platform data directory on an installed build,
// beside the config file on a portable one.
type Storage struct {
	DBPath string `json:"db_path"`
}

// #Engine is the audio engine's own tuning, mapped one-to-one onto
// core/dsp.EngineConfig at the services/tuner boundary. The engine depends on
// nothing in this package - these are the app's knobs on it - which is what
// keeps core/dsp liftable on its own. The defaults are the engine's own
// (core/dsp.DefaultEngineConfig); the ranges keep a typo from producing a
// window too short to resolve a reed or a hold no note could satisfy.
//
// This section is the engine's TIMINGS. The engine's deeper calibration (its
// detection, beat and pair thresholds) stays as documented constants in
// core/dsp: those are load-bearing and empirically fixed, and opening them to a
// config file would be a way to silently break reed detection.
type Engine struct {
	// The analysis window, in milliseconds. The highest-leverage knob: it sets
	// the frequency resolution and how close two reeds of a musette may sit and
	// still be told apart, and the slowest beat the engine can honestly measure.
	// Three seconds is the balance the detector is calibrated around; move it far
	// and a merged pair stops looking like one.
	FineWindowMs int64 `json:"fine_window_ms"`

	// How long a reading must hold still, in milliseconds, before the engine
	// reports a stable lock. A take is recorded on the lock; in calibration the
	// capture opens on it. Lower it and the tuner commits sooner but to a less
	// settled reading.
	LockHoldMs int64 `json:"lock_hold_ms"`

	// How far any reed may drift, in hertz, between fine results and still count
	// as the same reading. Raise it to keep the lock through a wavering note;
	// lower it to demand a stiller one.
	LockEpsilonHz float64 `json:"lock_epsilon_hz"`
}

type ThemeMode string

type AccentMode string

type Language string
