// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function LogDebug(message: string, fields: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(4286452005, message, fields);
}

export function LogError(message: string, fields: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(1421587620, message, fields);
}

export function LogInfo(message: string, fields: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(336333530, message, fields);
}

export function LogWarn(message: string, fields: { [_ in string]?: any }): $CancellablePromise<void> {
    return $Call.ByID(1254306962, message, fields);
}
