// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service owns the window title. Bindings each run on their own goroutine, so
 * all methods are safe to call concurrently.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Set replaces the phrase shown after the base name. Empty restores the bare
 * base name. The error return is for the bindings, which read better as a
 * promise on the TS side.
 */
export function Set(text: string): $CancellablePromise<void> {
    return $Call.ByID(3510710200, text);
}

/**
 * Title returns the title as it currently resolves.
 */
export function Title(): $CancellablePromise<string> {
    return $Call.ByID(2028415966);
}
