// Code generated by s99wails frontendgen. DO NOT EDIT.

// appTitle.ts
import { isWails } from './environment'

/** Matches the s99wails services/title bindings surface. */
export interface AppTitleSink {
  Set: (text: string) => Promise<void> | unknown
}

/**
 * Pushes the window title phrase to the desktop title service. The app name is
 * prepended on the Go side, so this takes only the part that says what the user
 * is doing; an empty string restores the bare app name.
 *
 * Pushes are coalesced within a microtask, and text identical to the last
 * confirmed title is dropped. Only a successful push updates the confirmed
 * text, so a failed one stays eligible for the next call; nothing is requeued
 * on failure, so a rejecting binding is not hammered in a loop.
 *
 * No-op on the web, where there is no window to title.
 */
export function useAppTitle(sink: AppTitleSink): { setTitle: (text: string) => void } {
  if (!isWails()) {
    return { setTitle: () => {} }
  }

  let confirmed: string | null = null
  let desired: string | null = null
  let inFlight = false
  let scheduled = false

  const flush = () => {
    if (inFlight || desired === null || desired === confirmed) return

    const next = desired
    desired = null
    inFlight = true

    // sink.Set may throw synchronously instead of rejecting. Normalize it, or
    // the throw escapes flush() as an unhandled rejection and inFlight never
    // resets, because its .finally() never runs.
    let result: Promise<void> | unknown
    try {
      result = sink.Set(next)
    } catch (err) {
      result = Promise.reject(err)
    }

    void Promise.resolve(result)
      .then(() => {
        confirmed = next
      })
      .catch(() => {
        // Leave confirmed untouched so the dedupe check lets a retry through.
      })
      .finally(() => {
        inFlight = false
        // Resume with whatever setTitle queued while this push was in flight.
        flush()
      })
  }

  return {
    setTitle: (text: string) => {
      desired = text
      if (scheduled) return
      scheduled = true
      void Promise.resolve().then(() => {
        scheduled = false
        flush()
      })
    },
  }
}
