// Code generated by s99wails frontendgen. DO NOT EDIT.

// contrast.ts
//
// The black-or-white foreground that reads on a chosen colour, and the WCAG luminance behind it.
// Framework-free: a Vuetify app gets on-colours from its theme, but a canvas, a report or a
// plain-CSS app has to compute this, and every desktop app otherwise re-derives the same lines.

export interface Rgb {
  r: number;
  g: number;
  b: number;
}

/** Parse #rgb / #rrggbb (with or without the hash, any alpha ignored) to 0..255 channels, or null. */
export function parseHex(hex: string): Rgb | null {
  const m = /^#?([0-9a-f]{3}|[0-9a-f]{6})/i.exec(hex.trim());
  if (!m) return null;
  const h = m[1].length === 3 ? m[1].replace(/./g, (c) => c + c) : m[1];
  const n = parseInt(h, 16);
  return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255 };
}

/** WCAG relative luminance, 0 (black) .. 1 (white). */
export function relativeLuminance({ r, g, b }: Rgb): number {
  const lin = (c: number) => {
    const v = c / 255;
    return v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4;
  };
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b);
}

/**
 * The foreground (dark or light) that reads on a fill, by whichever gives more contrast. The 0.179
 * crossover is where WCAG contrast against white equals contrast against black; luminance is
 * monotonic, so a single threshold decides. Unparseable input falls back to the light foreground.
 */
export function foregroundOn(
  hex: string,
  opts?: { light?: string; dark?: string },
): string {
  const light = opts?.light ?? "#ffffff";
  const dark = opts?.dark ?? "#000000";
  const rgb = parseHex(hex);
  if (!rgb) return light;
  return relativeLuminance(rgb) > 0.179 ? dark : light;
}
