// Code generated by s99wails frontendgen. DO NOT EDIT.

// environment.ts

/** True when running inside a Wails webview. */
export function isWails(): boolean {
  return typeof window !== 'undefined' && '_wails' in window
}

/**
 * Single place that answers "web or desktop?". Do not repeat the check in
 * components; Wails-specific behavior belongs behind composables.
 */
export function useWailsEnvironment() {
  const isDesktop = isWails()

  return {
    isDesktop,
    isWeb: !isDesktop,
  }
}
