// Code generated by s99wails frontendgen. DO NOT EDIT.

// index.ts
export { isWails, useWailsEnvironment } from "./environment";
export {
  useDesktopLocaleSync,
  type DesktopLocaleSyncOptions,
} from "./localeSync";
export {
  useSystemTheme,
  THEME_CHANGED_EVENT,
  type SystemThemeInfo,
  type SystemThemeOptions,
} from "./systemTheme";
export { installFrontendLogBridge, type FrontendLogSink } from "./logBridge";
export { useAppTitle, type AppTitleSink } from "./appTitle";
export {
  foregroundOn,
  relativeLuminance,
  parseHex,
  type Rgb,
} from "./contrast";
export {
  resolveDesktopTheme,
  type DesktopTheme,
  type DesktopThemeInputs,
  type ThemeMode,
  type AccentMode,
} from "./resolveDesktopTheme";
