// Code generated by s99wails frontendgen. DO NOT EDIT.

// localeSync.ts
import { getCurrentInstance, onMounted, watch, type Ref } from 'vue'
import { isWails } from './environment'

export interface DesktopLocaleSyncOptions {
  /** The frontend's active locale (e.g. from useI18n()). */
  locale: Ref<string>
  /** Applies a locale on the frontend (e.g. i18n setLocale). */
  setLocale: (code: string) => unknown
  /** Reads the persisted language from the desktop config service. */
  getLanguage: () => Promise<string | null | undefined>
  /** Persists a language via the desktop config service. */
  setLanguage: (code: string) => Promise<unknown>
}

/**
 * Keeps the frontend locale and the desktop shell's persisted language
 * preference in agreement: adopts the persisted language at startup and
 * pushes in-app changes back so the Go side re-localizes native UI (tray
 * menus). No-op on the web. Call once from app setup; the desktop service
 * accessors are injected because bindings are app-specific.
 */
export function useDesktopLocaleSync(options: DesktopLocaleSyncOptions): void {
  if (!isWails()) return

  // Created synchronously so it binds to the caller's effect scope; a watch
  // created after an await escapes the scope and leaks.
  watch(options.locale, async (code) => {
    const current = await options.getLanguage()
    if (current === code) return
    await options.setLanguage(code)
  })

  const adopt = async () => {
    const persisted = await options.getLanguage()
    if (persisted && persisted !== options.locale.value) {
      await options.setLocale(persisted)
    }
  }

  if (getCurrentInstance()) {
    onMounted(() => { void adopt() })
  }
  else {
    void adopt()
  }
}
