// Code generated by s99wails frontendgen. DO NOT EDIT.

// resolveDesktopTheme.ts
//
// Folds a desktop app's stored theme preferences and the live desktop theme (useSystemTheme) into
// the two things a UI actually needs: which theme is up (light or dark) and the accent colour.
// Framework-neutral - it returns plain reactive values; the app maps them onto Vuetify, Tailwind,
// or bare CSS variables. The heuristics (auto follows the desktop, a custom accent wins, a
// built-in default stands when the desktop exposes none) are the same in every s99wails app.

import { computed, type ComputedRef, type Ref } from "vue";
import type { SystemThemeInfo } from "./systemTheme";

export type ThemeMode = "auto" | "light" | "dark";
export type AccentMode = "auto" | "custom";

export interface DesktopThemeInputs {
  /** The live desktop theme, from useSystemTheme. */
  system: Ref<SystemThemeInfo | null>;
  /** The app's theme preference: follow the desktop, or force light/dark. */
  mode: () => ThemeMode;
  /** The app's accent preference: follow the desktop's accent, or a custom colour. */
  accentMode: () => AccentMode;
  /** The custom accent hex, used when accentMode is 'custom'. */
  customAccent: () => string;
  /** The built-in accent per theme, used when following the desktop but it exposes none. */
  fallbackAccent: (isDark: boolean) => string;
}

export interface DesktopTheme {
  isDark: ComputedRef<boolean>;
  /** The resolved theme name. */
  themeName: ComputedRef<"light" | "dark">;
  /** The resolved accent for the current theme, always a concrete #rrggbb. */
  accent: ComputedRef<string>;
  /**
   * The accent for EITHER theme, for a UI that colours light and dark at once (e.g. Vuetify holds
   * both theme objects). Reads the current preferences, so call it inside a watch.
   */
  accentFor: (isDark: boolean) => string;
}

function normalizeHex(hex: string): string | null {
  const m = /^#?([0-9a-f]{6})/i.exec(hex.trim());
  return m ? `#${m[1]}` : null;
}

export function resolveDesktopTheme(inputs: DesktopThemeInputs): DesktopTheme {
  const isDark = computed(() => {
    const mode = inputs.mode();
    if (mode === "light") return false;
    if (mode === "dark") return true;
    return inputs.system.value?.dark_mode ?? false;
  });

  const themeName = computed<"light" | "dark">(() =>
    isDark.value ? "dark" : "light",
  );

  const accentFor = (dark: boolean): string => {
    if (inputs.accentMode() === "custom") {
      const hex = normalizeHex(inputs.customAccent());
      if (hex) return hex;
    } else {
      const sys = inputs.system.value;
      if (sys?.accent_watch_supported && sys.accent_color) {
        const hex = normalizeHex(sys.accent_color);
        if (hex) return hex;
      }
    }
    return inputs.fallbackAccent(dark);
  };

  const accent = computed(() => accentFor(isDark.value));

  return { isDark, themeName, accent, accentFor };
}
