// Code generated by s99wails frontendgen. DO NOT EDIT.

// systemTheme.ts
import { getCurrentInstance, onUnmounted, readonly, ref, type Ref } from 'vue'
import { Events } from '@wailsio/runtime'
import { isWails } from './environment'

/** Mirrors the Go accent.Info bindings model. */
export interface SystemThemeInfo {
  accent_color: string
  dark_mode: boolean
  scheme: 'no-preference' | 'light' | 'dark'
  accent_watch_supported: boolean
}

/** Event name emitted by the s99wails services/theme watcher. */
export const THEME_CHANGED_EVENT = 'theme:changed'

export interface SystemThemeOptions {
  /** Initial fetch, typically the ThemeService.GetTheme binding. */
  getTheme: () => Promise<SystemThemeInfo>
}

/**
 * Reactive system theme (dark mode + accent color) fed by the desktop
 * theme service and its theme:changed events. Stays null on the web;
 * fall back to prefers-color-scheme there. The getTheme binding is
 * injected because bindings are app-specific.
 */
export function useSystemTheme(options: SystemThemeOptions): { theme: Readonly<Ref<SystemThemeInfo | null>> } {
  const theme = ref<SystemThemeInfo | null>(null)

  if (!isWails()) {
    return { theme: readonly(theme) }
  }

  void options.getTheme().then((info) => {
    theme.value = info
  })

  const unsubscribe = Events.On(THEME_CHANGED_EVENT, (event: { data?: unknown }) => {
    const payload = Array.isArray(event.data) ? event.data[0] : event.data
    if (payload) {
      theme.value = payload as SystemThemeInfo
    }
  })

  if (getCurrentInstance()) {
    onUnmounted(unsubscribe)
  }

  return { theme: readonly(theme) }
}
